### ISSUE TITLE
Players can propsurf still

### ISSUE THREAD

**Issue by HugoCortell** [ExtendRealityLtd/Tilia.Trackers.PseudoBody.Unity#34]
### Environment

* Code source: tilia package on the manifest
* Code version:  1.1.4
* Platform version: 2019.4.1f1
* 3rd party dependencies: Most other tilia packages are also installed, except the teleport related stuff.

### Steps to reproduce

The latest version attempted to fix this, and indeed it is fixed, **_IF_** the player picks the object up as normal and then moves it into his body.  

The setup is the following: Literally the one from the braindump but without any pointers or teleportation stuff, the movement is the slide movement.
https://cdn.discordapp.com/attachments/716792975228665868/730132008126251018/unknown.png

Once you have that, create an interactable cube adn place it on the floor, you are done.

-

There are two ways to break this, the first way is to stand on top of the object or otherwise have your rigidbody DIRECTLY touch the rigidbody of the object to be picked up. It will not disable collisions and will send the player into outer orbit.

The second way is to update the speed modifier in the player's slide movement prefab, it will then re-enable collisions and push the player once again until the object is dropped and picked up again.  

### Expected behavior

No collisions when picked up no matter what.

### Current behavior
Players become part of the new Unity Space Program™️, they get launched into space or otherwise are pushed by the cube.

### Recordings
I will later be making a recording of this behaviour and be sharing it on the VRTK discord.

**Comment by thestonefox** [comment]
You need to provide clear steps to reproduce... e.g.

i.e. how you set up the example that causes the break (step by step)
then the steps you do whilst running the scene to display the issue.

Otherwise it's not easy to recreate the issue and most likely won't be looked at.

**Comment by HugoCortell** [comment]
> 
> 
> You need to provide clear steps to reproduce... e.g.
> 
> i.e. how you set up the example that causes the break (step by step)
> then the steps you do whilst running the scene to display the issue.
> 
> Otherwise it's not easy to recreate the issue and most likely won't be looked at.

Alright, later once iv got unity open ill go ahead an explain my set up with greater detail.

**Comment by HugoCortell** [comment]
> 
> 
> You need to provide clear steps to reproduce... e.g.
> 
> i.e. how you set up the example that causes the break (step by step)
> then the steps you do whilst running the scene to display the issue.
> 
> Otherwise it's not easy to recreate the issue and most likely won't be looked at.

All done, updated.
Hopefully this will be enough, otherwise in 2 or 3 hours ill go ahead and record some footage and stuff.

**Comment by HugoCortell** [comment]
Here are the recordings: https://gofile.io/d/Md7uEl
There are two bugs, download the relevant one.

**Comment by HugoCortell** [comment]
It has been a month since I posted this, might as well update on how updates and stuff have affected the bug.
As it stands, for the time being, it appears that it only now pushes the player if he is not grounded.

If the player is standing atop the object when picking it up, falling, or walking up a ramp, he will be shot into outer space.

**Comment by HugoCortell** [comment]
Yeah, layers do the work fine enough.
