### ISSUE TITLE
Smooth Collisions

### ISSUE THREAD

**Issue by HugoCortell** [ExtendRealityLtd/Tilia.Trackers.PseudoBody.Unity#45]
## Is your feature request related to a problem?

I'm always frustrated when I come close to a wall and suddenly I teleport 5 feet away, or go lean to grab an object and I start getting a seizure. 

## Describe the solution you'd like

Id like to make it work like most other VR games, it just stops you without needing to teleport you away, like a physics collision.
No jitter, just normal collisions.

## Describe alternatives you've considered

I could not find an alternative that worked.

## Additional context

I feel like this should already be a thing, but the brain dump clearly shows the jitter too.

**Comment by thestonefox** [comment]
What do you have your `Source Thickness` on the `Pseudo Body Facade` set to?

**Comment by HugoCortell** [comment]
The earliest value I can remember was 0.25, but it had the jitter + some strange collision issues when it came to stairs so for a long time iv been using 0.45.

Values such as 0.15 make it nearly perfectly smooth but cause the player to get stuck in geometry that intersects (such as the edge between a wall and the floor).
Sometimes the player cant even escape after getting stuck, though I can get around that with the sprinting mechanic I added to my game.

**Comment by thestonefox** [comment]
Try the default value of `0.205`, that shouldn't have any jitter.

If you're trying to move up stairs, you're better off having a fake slope collider than attempting to move a user directly up a `0.45` y position in VR. most games fake stairs with a slope collider.

**Comment by HugoCortell** [comment]
I attempted 0.205 and the jitter was still there (though attmittedly it was far lesser), what concerns me about this value though is the fact that the player cannot use ramps, he just floats away like theres an invisible floor.
https://cdn.discordapp.com/attachments/716792975228665868/738545784479285308/ezgif.com-gif-maker.webp

**Comment by HugoCortell** [comment]
I have continued to test and found that matching the source thickness directly with the character controller radius removed nearly all stutter. I must mention however that one eye has the stutter while the other one does not, the right eye to be specific.

I sadly have yet to find a fix to the player straight up ignoring physics while on rams.
Have you been able to replicate this behaviour previously?

**Comment by HugoCortell** [comment]
More details per request of Ethan:
**Character Setup**  
https://cdn.discordapp.com/attachments/716792975228665868/740661702617727030/unknown.png  
https://cdn.discordapp.com/attachments/716792975228665868/740661655339270215/unknown.png  

**Collider Parameters**  
https://cdn.discordapp.com/attachments/716792975228665868/740662103614160906/unknown.png  
Note: I meassured it and it turned out to be a 20 degree angle ramp instead of 45.

**Comment by fight4dream** [comment]
> I attempted 0.205 and the jitter was still there (though admittedly it was far lesser), what concerns me about this value though is the fact that the player cannot use ramps, he just floats away like there's an invisible floor.
> https://cdn.discordapp.com/attachments/716792975228665868/738545784479285308/ezgif.com-gif-maker.webp

the current axis move is based on Transform Property Applier,
but the pseudo body is using physics when grounded.
as soon as the player use axis move to walk downhill, the transform apply is moving it forward on x-z plane,
then the pseudo body think he is now airborne, gravity works but the velocity was small so it is like floating.
axis move continuously transform apply forward, gravity will eventually catch up and make him grounded.
thus losing the downward velocity.
the overall result is the player seems dropping slowly while walking downhill.

**Comment by HugoCortell** [comment]
> Edit: even if the axis move uses physics add force, i think it will not fix this issue, as long as the axis move is only moving it on x-z plane

I agree with this assessment, it appears that the axis move is causing the issue here.
when I force airborne on ramps the problem nearly solves itself (even if it's not smooth).

**Comment by HugoCortell** [comment]
It seems I never updated this, so might as well.

The flickering is _**not solved**_, it only works on single-pass while in-engine. Builds still showcase the flickering.
I believe it might also be related to ([this](https://github.com/ExtendRealityLtd/VRTK/issues/1992)) but I'm not 100% sure.
(The behaviour is similar for the player's hands + grabbed objects but it also affects the camera and possibly collision detection).

Force airborne does not alleviate smoothness problems (same flickering as before) when moving against walls.

**Comment by HugoCortell** [comment]
I can confirm it is https://github.com/ExtendRealityLtd/VRTK/issues/1992.

**Comment by HugoCortell** [comment]
I have moved the issue to https://github.com/ExtendRealityLtd/VRTK/issues/2113 since its now outside the scope of this issue.
