### ISSUE TITLE
Skyrocketed if TrackedAlias is scaled up

### ISSUE THREAD

**Issue by fight4dream** [ExtendRealityLtd/Tilia.Trackers.PseudoBody.Unity#54]
### Environment

* Code source: github
* Code version: 316f1b3
* Platform version: Unity 2019.4.1f1
* 3rd party dependencies:

### Preface

A game was made with VRTK v3 previously, https://store.steampowered.com/app/566870/VR_Monster_Awakens/
It featured a large monster destroying the city. In particular, it can climb and uses BodyPhysics.
We want to remake the game in v4.

### Steps to reproduce

1. Setup Tilia UnityXR and TrackedAlias
2. Setup PsedoBody
3. Scale up the TrackedAlias to (3,3,3)
4. Play

### Expected behavior

It should behave the same as if the TrackedAlias is at its original scale.

### Current behavior

Player is launched into the air and fall back, repeatedly.

**Comment by thestonefox** [comment]
fixed with https://github.com/ExtendRealityLtd/Tilia.Trackers.PseudoBody.Unity/pull/83
