### ISSUE TITLE
Using PseudoBody with AxisMove allows Player to pass through walls

### ISSUE THREAD

**Issue by kevincastejon** [ExtendRealityLtd/Tilia.Trackers.PseudoBody.Unity#68]
### Environment

* Code source: tilia's github repos
* Code version: 
"io.extendreality.tilia.trackers.pseudobody.unity": "1.3.3"
"io.extendreality.tilia.locomotors.axismove.unity": "1.1.19",

* Platform version: 2019.4.13f1
* 3rd party dependencies: Oculus Integration 20.1

### Steps to reproduce

Follow the tutorial [Adding a PseudoBody](https://github.com/ExtendRealityLtd/Tilia.Trackers.PseudoBody.Unity/tree/master/Documentation/HowToGuides/AddingAPseudoBody) and add a AxisMove. Then try to collide with a wall by moving through the AxisMove. It won't collide.

Minimalist repo reproducing the issue : [https://github.com/kevincastejon/tilia-pseudobody-with-axismove](https://github.com/kevincastejon/tilia-pseudobody-with-axismove)

### Expected behavior

It should collide when moving through AxisMove as it does when moving head.

### Current behavior

It still collides when moving head but not when moving through AxisMove

**Comment by kevincastejon** [comment]
@thestonefox gave a temporary workaround:
- Add a Diverged event listener (_BEFORE_ the one that calls SolveBodyCollision), hook it up to the AxisMove gameobject SetActive method with false parameter.
- Add a Converged event listener , hook it up to the AxisMove gameobject SetActive method with true parameter.

as you can see on this [screenshot](https://raw.githubusercontent.com/kevincastejon/tilia-pseudobody-with-axismove/main/workaround.png)

I've updated the [minimalist repo](https://github.com/kevincastejon/tilia-pseudobody-with-axismove) with that workaround.

**Comment by thestonefox** [comment]
I've got a potential fix for this by adding a new `StillDiverged` event that keeps emitting if you are still diverged

so you get the initial `Diverged` event when you first diverge, and a `Converged` event when you stop diverging, and a continuous `StillDiverged` event if you keep diverging after every frame.

Similar to Unity collision detection of `CollisionStart` `CollisionStay` `CollisionEnd`

**Comment by thestonefox** [comment]
Pull request with fix. Just move the SolveBodyCollisions to the StillDiverged event

https://github.com/ExtendRealityLtd/Tilia.Trackers.PseudoBody.Unity/pull/69

**Comment by thestonefox** [comment]
If this works then before I merge this I'll add another commit with an update to the howtoguide

**Comment by chrisandrews10007** [comment]
I have tried the potential fix as suggested Nov-7. I could not find any screenshot of how it was set up however, so I have set it up on the PseudoBody as shown in the image below, however still can pass thru Solid objects whilst using Axis Move. 
![PassingThruCollider](https://user-images.githubusercontent.com/58829713/101533619-12fae700-39bc-11eb-9e71-d02ad0f7c625.png)
