### ISSUE TITLE
Add pseudobody example with Head + Torso, optionaly tail

### ISSUE THREAD

**Issue by studentutu** [ExtendRealityLtd/Tilia.Trackers.PseudoBody.Unity#72]
Just need more examples on how to properly use pseudobody. For example, interactions have already an object where you would put your custom avatar for hands, would be nice to have something like this for pseudobody

**Comment by thestonefox** [comment]
Not sure what this request is asking for

**Comment by studentutu** [comment]
@thestonefox just an example of how to use pseudobody with a torso avatar

**Comment by thestonefox** [comment]
what has the pseudo body got to do with a torso avatar?

**Comment by studentutu** [comment]
@thestonefox I thought that that is a primary function of it... so where do you place Torso Avatar? how to do Torso with Tilia?

**Comment by thestonefox** [comment]
No, the pseudo body has nothing to do with avatars, it provides a collidable body that follows your presence around the scene so you can implement physics against the player.

```
The Pseudo Body prefab provides a spatial virtual representation of a user in the physical world. It allows for the detection of collisions within the virtual world and to determine when the virtual representation location diverges from the physical location.
```

If you wanted to add a torso avatar then you'd just get it to follow the headset around but ignore the X,Z rotation (and offset it down on the Y axis)
